=====================
multiplies 2 matrices
=====================

>>> matrix_mul = __import__("101-lazy_matrix_mul").lazy_matrix_mul

>>> print(matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]]))
[[ 7 10]
 [15 22]]

>>> print(matrix_mul((1, 2 ,3, 4), [[1, 2], [3, 4]]))
Traceback (most recent call last):
ValueError: shapes (4,) and (2,2) not aligned: 4 (dim 0) != 2 (dim 0)

>>> print(matrix_mul([[1, 2] ,[3, 4]], (1, 2, 3, 4)))
Traceback (most recent call last):
ValueError: shapes (2,2) and (4,) not aligned: 2 (dim 1) != 4 (dim 0)

>>> print(matrix_mul([1, 2 ,3, 4], [[1, 2], [3, 4]]))
Traceback (most recent call last):
ValueError: shapes (4,) and (2,2) not aligned: 4 (dim 0) != 2 (dim 0)

>>> print(matrix_mul([[1, 2] ,[3, 4]], [1, 2, 3, 4]))
Traceback (most recent call last):
ValueError: shapes (2,2) and (4,) not aligned: 2 (dim 1) != 4 (dim 0)

>>> print(matrix_mul([], [[2, 3], [4, 5]]))
Traceback (most recent call last):
ValueError: shapes (0,) and (2,2) not aligned: 0 (dim 0) != 2 (dim 0)

>>> print(matrix_mul([[]], [[2, 3], [4, 5]]))
Traceback (most recent call last):
ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

>>> print(matrix_mul([[2, 3], [4, 5]], []))
Traceback (most recent call last):
ValueError: shapes (2,2) and (0,) not aligned: 2 (dim 1) != 0 (dim 0)

>>> print(matrix_mul([[2, 3], [4, 5]], [[]]))
Traceback (most recent call last):
ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

>>> print(matrix_mul([[1, 2], ["3", 4]], [[1, 2], [3, 4]]))
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> print(matrix_mul([[1, 2], ["str", 4]], [[1, 2], [3, 4]]))
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> print(matrix_mul([[1, 2], [3, 4]], [[1, 2], ["3", 4]]))
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> print(matrix_mul([[1, 2], [3, 4]], [[1, 2], ["str", 4]]))
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> print(matrix_mul([[1, 2, 9], [3, 4, 2], [7, 8]], [[1, 2], [3, 4]]))
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> print(matrix_mul([[5, 6, 10], [7, 8]], [[5, 6], [7, 8]]))
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> print(matrix_mul([[5, 6], [7, 8]], [[5, 6, 1], [7, 8]]))
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> print(matrix_mul([[3, 5], [3 ,6]]))
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

>>> print(matrix_mul())
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

>>> print(matrix_mul([[11, 12, 14], [11, 12, 14]], [[4, 2, 5], [1, 2, 3]]))
Traceback (most recent call last):
ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

